"""
=============================================================
 predict_toolbox_sample.py
 Predict the shape of any radar heatmap .mat file

 Works with files generated by:
   - radar_stl_to_heatmap.m       (saves stl_heatmap_*.mat)
   - radar_toolbox_predict_sample.m (saves toolbox_sample_*.mat)
   - process_real_data.m            (saves real_heatmap.mat)

 Usage:
   Single prediction:
     python predict_toolbox_sample.py --file stl_heatmap_circle_0deg.mat

   Specify a different model:
     python predict_toolbox_sample.py --file stl_heatmap_square_0deg.mat
                                      --model radar_shape_model_N8.pt

   Batch predict all .mat files in current folder:
     python predict_toolbox_sample.py --batch

   Batch with specific model:
     python predict_toolbox_sample.py --batch --model radar_shape_model_N32.pt

 Requirements:
   pip install torch scipy numpy matplotlib

 Project: Radar Object Detection + ML (Junior IW)
=============================================================
"""

import scipy.io
import numpy as np
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
import argparse
import os
import glob

# ── Device ──────────────────────────────────────────────────
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Device: {device}")

# ── Class names — must match MATLAB label order exactly ─────
CLASS_NAMES  = ['Circle', 'Square', 'Rectangle', 'Triangle', 'Oval']
N_CLASSES    = len(CLASS_NAMES)
CLASS_COLORS = ['#3498DB', '#E74C3C', '#2ECC71', '#9B59B6', '#F39C12']


# ============================================================
#  SECTION 1: MODEL ARCHITECTURE
#  Must be byte-for-byte identical to radar_shape_simple_cnn.py
# ============================================================

class ShapeCNN(nn.Module):
    """
    2D CNN for radar shape classification.
    Architecture must match the training script exactly.
    """
    def __init__(self, n_classes=5):
        super().__init__()

        self.features = nn.Sequential(
            # Block 1
            nn.Conv2d(1,  16,  kernel_size=7, padding=3),
            nn.BatchNorm2d(16),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2, 2),

            # Block 2
            nn.Conv2d(16, 32,  kernel_size=5, padding=2),
            nn.BatchNorm2d(32),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2, 2),

            # Block 3
            nn.Conv2d(32, 64,  kernel_size=3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2, 2),

            # Block 4
            nn.Conv2d(64, 128, kernel_size=3, padding=1),
            nn.BatchNorm2d(128),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2, 2),
        )

        self.gap = nn.AdaptiveAvgPool2d(1)

        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear(128, 64),
            nn.ReLU(inplace=True),
            nn.Dropout(0.4),
            nn.Linear(64, n_classes),
        )

    def forward(self, x):
        x = self.features(x)
        x = self.gap(x)
        x = self.classifier(x)
        return x


# ============================================================
#  SECTION 2: LOAD MODEL
# ============================================================

def load_model(model_path):
    """
    Load a trained ShapeCNN from a .pt file.

    Args:
        model_path : path to radar_shape_model_N*.pt

    Returns:
        model : loaded ShapeCNN in eval mode
        ckpt  : checkpoint dict with metadata
    """
    if not os.path.exists(model_path):
        raise FileNotFoundError(
            f"\nModel not found: {model_path}\n"
            f"Train it first:\n"
            f"  python radar_shape_simple_cnn.py --single radar_shapes_N16.mat\n"
        )

    ckpt  = torch.load(model_path, map_location=device)
    model = ShapeCNN(n_classes=ckpt['n_classes'])
    model.load_state_dict(ckpt['model_state_dict'])
    model = model.to(device)
    model.eval()

    print(f"\nModel loaded  : {model_path}")
    print(f"  N_ant       : {ckpt.get('n_ant', 'unknown')}")
    print(f"  Accuracy    : {ckpt.get('test_accuracy', 0)*100:.1f}%")
    print(f"  Classes     : {ckpt.get('class_names', CLASS_NAMES)}\n")

    return model, ckpt


# ============================================================
#  SECTION 3: LOAD HEATMAP
#
#  Handles all three MATLAB file formats:
#    stl_heatmap_*.mat        from radar_stl_to_heatmap.m
#    toolbox_sample_*.mat     from radar_toolbox_predict_sample.m
#    real_heatmap.mat         from process_real_data.m
# ============================================================

def load_heatmap(mat_path):
    """
    Load a Range-Angle heatmap from a MATLAB .mat file.

    Accepts files from any of the three MATLAB generators.
    Automatically extracts ground truth label if present.

    Returns:
        heatmap    : numpy float32 [range_bins x angle_bins]
        range_axis : numpy float32 [range_bins] or None
        ang_axis   : numpy float32 [angle_bins] or None
        true_shape : string ground truth label or None
    """
    if not os.path.exists(mat_path):
        raise FileNotFoundError(
            f"\nHeatmap file not found: {mat_path}\n"
            f"Generate it first with one of:\n"
            f"  radar_stl_to_heatmap.m\n"
            f"  radar_toolbox_predict_sample.m\n"
        )

    data = scipy.io.loadmat(mat_path)
    keys = [k for k in data.keys() if not k.startswith('_')]

    # ── Load heatmap array ───────────────────────────────────
    # Try field names in order of preference
    heatmap = None
    for field in ['RA_normalised', 'RA_map']:
        if field in data:
            heatmap = data[field].astype(np.float32)
            # Normalise if not already in [0,1]
            if heatmap.max() > 1.01:
                heatmap = heatmap / (heatmap.max() + 1e-9)
            break

    if heatmap is None:
        raise KeyError(
            f"\nNo heatmap found in: {mat_path}\n"
            f"Available keys: {keys}\n"
            f"Expected one of: RA_normalised, RA_map\n"
            f"Regenerate the file in MATLAB."
        )

    # ── Load axes ────────────────────────────────────────────
    range_axis = data['range_axis'].flatten() \
                 if 'range_axis' in data else None
    ang_axis   = data['ang_axis'].flatten() \
                 if 'ang_axis'   in data else None

    # ── Extract ground truth label ───────────────────────────
    # Different MATLAB scripts use different field names
    true_shape = None
    for label_field in ['TEST_SHAPE', 'TRUE_SHAPE', 'true_shape', 'shape']:
        if label_field in data:
            raw = data[label_field]
            try:
                # scipy loads MATLAB strings as object arrays
                if hasattr(raw, 'flat'):
                    true_shape = str(raw.flat[0]).strip().lower()
                else:
                    true_shape = str(raw).strip().lower()
                # Clean up any extra brackets or quotes
                true_shape = true_shape.strip("[]'\" ")
                if true_shape:
                    break
            except Exception:
                continue

    # ── Extract range and orientation metadata ───────────────
    true_range = None
    for rng_field in ['TEST_RANGE', 'OBJ_RANGE']:
        if rng_field in data:
            true_range = float(data[rng_field].flat[0])
            break

    true_ori = None
    for ori_field in ['TEST_ORIENTATION', 'OBJ_ORIENTATION']:
        if ori_field in data:
            true_ori = float(data[ori_field].flat[0])
            break

    # ── Print summary ────────────────────────────────────────
    print(f"File loaded   : {os.path.basename(mat_path)}")
    print(f"  Heatmap     : {heatmap.shape}")
    print(f"  Value range : [{heatmap.min():.4f}, {heatmap.max():.4f}]")
    print(f"  True shape  : {true_shape if true_shape else 'not saved in file'}")
    if true_range: print(f"  True range  : {true_range} m")
    if true_ori:   print(f"  True orient : {true_ori} deg")

    return heatmap, range_axis, ang_axis, true_shape


# ============================================================
#  SECTION 4: PREPROCESS AND PREDICT
# ============================================================

def predict(heatmap, model):
    """
    Run the trained model on one heatmap.

    Preprocesses the heatmap to match training format:
      - Normalise to [0,1]
      - Resize to [512 x 256] if needed
      - Add batch and channel dimensions

    Returns:
        pred_name  : predicted shape name string
        confidence : float 0-1
        all_probs  : dict of class name -> probability
        hm         : preprocessed heatmap numpy array
    """
    hm = heatmap.astype(np.float32)

    # Normalise
    if hm.max() > 0:
        hm = hm / hm.max()

    # Resize to match training dimensions if needed
    if hm.shape != (512, 256):
        from scipy.ndimage import zoom
        zoom_r = 512 / hm.shape[0]
        zoom_a = 256 / hm.shape[1]
        hm     = zoom(hm, (zoom_r, zoom_a), order=1)
        if hm.max() > 0:
            hm = hm / hm.max()
        print(f"  Resized to  : {hm.shape}")

    # Build tensor [1 x 1 x 512 x 256]
    tensor = torch.tensor(hm, dtype=torch.float32)
    tensor = tensor.unsqueeze(0).unsqueeze(0).to(device)

    # Forward pass
    with torch.no_grad():
        logits = model(tensor)
        probs  = torch.softmax(logits, dim=1).cpu().numpy()[0]

    pred_idx   = int(np.argmax(probs))
    pred_name  = CLASS_NAMES[pred_idx]
    confidence = float(probs[pred_idx])
    all_probs  = {CLASS_NAMES[i]: float(probs[i])
                  for i in range(N_CLASSES)}

    return pred_name, confidence, all_probs, hm


# ============================================================
#  SECTION 5: PRINT AND VISUALISE RESULT
# ============================================================

def show_result(hm, pred_name, confidence, all_probs,
                true_shape=None, range_axis=None, ang_axis=None,
                filename=''):
    """
    Print prediction to console and display a figure.

    Shows the input heatmap alongside a probability bar chart.
    Title is green for correct, red for wrong, black if unknown.
    """
    # Determine correct / wrong / unknown
    correct = None
    if true_shape is not None:
        correct = pred_name.lower() == true_shape.lower()

    # ── Console output ───────────────────────────────────────
    print(f"\n{'='*52}")
    print(f"  RADAR SHAPE PREDICTION RESULT")
    print(f"{'='*52}")
    if filename:
        print(f"  File        : {os.path.basename(filename)}")
    if true_shape is not None:
        tag = 'CORRECT' if correct else 'WRONG'
        print(f"  True shape  : {true_shape.capitalize()}")
        print(f"  Prediction  : {pred_name}  [{tag}]")
    else:
        print(f"  Prediction  : {pred_name}")
    print(f"  Confidence  : {confidence*100:.1f}%")
    print(f"\n  All class probabilities:")
    for name, prob in sorted(all_probs.items(), key=lambda x: -x[1]):
        bar = 'X' * int(prob * 32)
        print(f"    {name:12s}: {prob*100:5.1f}%  {bar}")
    print(f"{'='*52}\n")

    # ── Figure ───────────────────────────────────────────────
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))
    fig.patch.set_facecolor('white')

    # Title colour: green=correct, red=wrong, black=unknown
    if correct is True:
        title_color = 'green'
    elif correct is False:
        title_color = 'red'
    else:
        title_color = 'black'

    title = f"Prediction: {pred_name}  ({confidence*100:.1f}% confidence)"
    if true_shape is not None:
        tag    = 'CORRECT' if correct else 'WRONG'
        title += f"  --  {tag}"
    fig.suptitle(title, fontsize=13, fontweight='bold',
                 color=title_color)

    # Heatmap panel
    x_extent = [ang_axis[0],   ang_axis[-1]]   \
               if ang_axis   is not None else [0, hm.shape[1]]
    y_extent = [range_axis[0], range_axis[-1]] \
               if range_axis is not None else [0, hm.shape[0]]

    im = ax1.imshow(
        20 * np.log10(hm + 1e-6),
        cmap='jet', aspect='auto',
        extent=[x_extent[0], x_extent[1],
                y_extent[0], y_extent[1]],
        vmin=-40, vmax=0, origin='lower'
    )
    plt.colorbar(im, ax=ax1, label='Magnitude (dB)')
    ax1.set_xlabel('Angle (degrees)' if ang_axis   is not None else 'Angle bins')
    ax1.set_ylabel('Range (m)'       if range_axis is not None else 'Range bins')
    ax1.set_title('Input Range-Angle Heatmap')
    if ang_axis is not None:
        ax1.set_xlim([-90, 90])

    # Probability bar chart
    names      = CLASS_NAMES
    probs_list = [all_probs[n] for n in names]
    colors     = CLASS_COLORS
    pred_idx   = CLASS_NAMES.index(pred_name)

    bars = ax2.barh(names, [p*100 for p in probs_list],
                    color=colors, edgecolor='white', height=0.6)

    # Highlight predicted bar with black border
    bars[pred_idx].set_edgecolor('black')
    bars[pred_idx].set_linewidth(2.5)

    # Add percentage labels
    for b, p in zip(bars, probs_list):
        ax2.text(b.get_width() + 1,
                 b.get_y() + b.get_height() / 2,
                 f'{p*100:.1f}%',
                 va='center', fontsize=9)

    ax2.set_xlabel('Confidence (%)')
    ax2.set_xlim([0, 118])
    ax2.set_title('Class Probabilities')
    ax2.grid(axis='x', alpha=0.3)
    ax2.axvline(50, color='gray', linestyle='--', alpha=0.5,
                linewidth=1, label='50% threshold')

    plt.tight_layout()
    out_file = 'prediction_result.png'
    plt.savefig(out_file, dpi=150, bbox_inches='tight')
    plt.show()
    print(f"Figure saved: {out_file}")


# ============================================================
#  SECTION 6: BATCH PREDICTION
#
#  Finds all .mat files in the current folder matching
#  stl_heatmap_*.mat  OR  toolbox_sample_*.mat
#  and predicts each one, printing a summary table.
# ============================================================

def batch_predict(model_path):
    """
    Predict all heatmap .mat files in the current folder.
    Searches for both stl_heatmap_*.mat and toolbox_sample_*.mat files.
    Prints a summary table with true vs predicted labels.
    """
    # Collect all relevant .mat files
    patterns = ['stl_heatmap_*.mat', 'toolbox_sample_*.mat']
    all_files = []
    for pat in patterns:
        all_files.extend(sorted(glob.glob(pat)))

    # Remove duplicates preserving order
    seen  = set()
    files = []
    for f in all_files:
        if f not in seen:
            seen.add(f)
            files.append(f)

    if not files:
        print("\nNo heatmap files found in current folder.")
        print("Expected files matching:")
        for p in patterns:
            print(f"  {p}")
        print("\nGenerate them first with:")
        print("  radar_stl_to_heatmap.m")
        print("  radar_toolbox_predict_sample.m")
        return

    # Load model once
    model, ckpt = load_model(model_path)

    print(f"\n{'='*72}")
    print(f"  BATCH PREDICTION  |  {len(files)} files  |  "
          f"Model: {os.path.basename(model_path)}")
    print(f"{'='*72}")
    print(f"  {'Filename':38s} | {'True':12s} | {'Predicted':12s} | "
          f"{'Conf':6s} | Result")
    print(f"  {'-'*70}")

    correct_count = 0
    known_count   = 0
    results       = []

    for fpath in files:
        try:
            heatmap, range_axis, ang_axis, true_shape = \
                load_heatmap(fpath)
            pred_name, confidence, all_probs, hm = \
                predict(heatmap, model)

            correct = None
            tag     = '  --  '
            if true_shape is not None:
                correct = pred_name.lower() == true_shape.lower()
                tag     = 'CORRECT' if correct else 'WRONG  '
                known_count += 1
                if correct:
                    correct_count += 1

            true_str = true_shape.capitalize() \
                       if true_shape else 'unknown'
            fname    = os.path.basename(fpath)

            print(f"  {fname:38s} | {true_str:12s} | "
                  f"{pred_name:12s} | {confidence*100:5.1f}% | {tag}")

            results.append({
                'file'      : fpath,
                'true'      : true_shape,
                'pred'      : pred_name,
                'confidence': confidence,
                'correct'   : correct,
            })

        except Exception as e:
            print(f"  {'ERROR':38s} | {fpath}: {e}")

    # Summary line
    print(f"  {'-'*70}")
    if known_count > 0:
        pct = correct_count / known_count * 100
        print(f"\n  Result: {correct_count}/{known_count} correct  "
              f"({pct:.0f}%)")
    else:
        print(f"\n  {len(files)} files predicted  "
              f"(no ground truth labels found)")
    print(f"{'='*72}\n")

    return results


# ============================================================
#  SECTION 7: MAIN ENTRY POINT
# ============================================================

if __name__ == '__main__':

    parser = argparse.ArgumentParser(
        description='Predict shape from radar Range-Angle heatmap'
    )
    parser.add_argument(
        '--file',
        type=str,
        default=None,
        metavar='FILE',
        help=(
            'Path to .mat heatmap file '
            '(stl_heatmap_*.mat or toolbox_sample_*.mat)'
        )
    )
    parser.add_argument(
        '--model',
        type=str,
        default='radar_shape_model_N16.pt',
        metavar='MODEL',
        help='Path to trained model .pt file (default: N16)'
    )
    parser.add_argument(
        '--batch',
        action='store_true',
        help=(
            'Predict all stl_heatmap_*.mat and '
            'toolbox_sample_*.mat files in current folder'
        )
    )
    args = parser.parse_args()

    if args.batch:
        # ── Batch mode ───────────────────────────────────────
        batch_predict(args.model)

    elif args.file:
        # ── Single file mode ─────────────────────────────────
        model, _  = load_model(args.model)
        heatmap, range_axis, ang_axis, true_shape = \
            load_heatmap(args.file)
        pred_name, confidence, all_probs, hm = \
            predict(heatmap, model)
        show_result(
            hm, pred_name, confidence, all_probs,
            true_shape  = true_shape,
            range_axis  = range_axis,
            ang_axis    = ang_axis,
            filename    = args.file,
        )

    else:
        # ── No arguments — show usage ─────────────────────────
        print("\nNo file specified. Examples:")
        print()
        print("  Single prediction:")
        print("    python predict_toolbox_sample.py "
              "--file stl_heatmap_circle_0deg.mat")
        print()
        print("  Different model:")
        print("    python predict_toolbox_sample.py "
              "--file stl_heatmap_square_0deg.mat "
              "--model radar_shape_model_N8.pt")
        print()
        print("  Batch — predict all heatmap files:")
        print("    python predict_toolbox_sample.py --batch")
        print()
        print("  Batch with specific model:")
        print("    python predict_toolbox_sample.py --batch "
              "--model radar_shape_model_N32.pt")
        print()

        # Auto-detect and run if exactly one heatmap file exists
        candidates = (glob.glob('stl_heatmap_*.mat') +
                      glob.glob('toolbox_sample_*.mat'))
        if len(candidates) == 1:
            print(f"Found one heatmap file: {candidates[0]}")
            print("Running prediction automatically...\n")
            model, _  = load_model(args.model)
            heatmap, range_axis, ang_axis, true_shape = \
                load_heatmap(candidates[0])
            pred_name, confidence, all_probs, hm = \
                predict(heatmap, model)
            show_result(
                hm, pred_name, confidence, all_probs,
                true_shape = true_shape,
                range_axis = range_axis,
                ang_axis   = ang_axis,
                filename   = candidates[0],
            )
        elif len(candidates) > 1:
            print(f"Found {len(candidates)} heatmap files.")
            print("Use --batch to predict all of them.")
