"""
=============================================================
 radar_shape_simple_cnn.py
 Radar Shape Classification — One Model Per Antenna Count

 Task   : Classify shape only
 Classes: Circle, Square, Rectangle, Triangle, Oval (5)
 Input  : Range-Angle heatmap [512 × 256]
 Output : Shape class (0-4)

 New in this version:
   Trains one ShapeCNN per antenna dataset file
   (radar_shapes_N4.mat, N8.mat, N16.mat, N32.mat)
   Then plots accuracy vs antenna count comparison.

 Usage:
   # Train all antenna experiments:
   python radar_shape_simple_cnn.py

   # Train on a single file only:
   python radar_shape_simple_cnn.py --single radar_shapes_N16.mat

 Requirements:
   pip install torch scipy numpy matplotlib seaborn scikit-learn

 Project: Radar Object Detection + ML (Junior IW)
=============================================================
"""

import scipy.io
import h5py
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, classification_report
import time
import os
import csv
import random
import argparse

# ── Reproducibility / multi-seed configuration ───────────────
# Each antenna experiment is trained once PER SEED so that test
# accuracy can be reported as mean ± std across independent runs.
# With only ~2,160 samples, a single seed's test accuracy has
# several percentage points of noise; averaging tightens the
# confidence interval enough to support claims about the best
# antenna count.
#
# Override with --seeds 0,1,2 from the command line.
SEEDS = [0, 1, 2, 3, 4]


def set_seed(seed):
    """Seed torch, numpy and random for one training run."""
    torch.manual_seed(seed)
    np.random.seed(seed)
    random.seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

# ── Device ──────────────────────────────────────────────────
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Device: {device}\n")

# ── Class names — must match MATLAB label order ──────────────
CLASS_NAMES  = ['Circle', 'Square', 'Rectangle', 'Triangle', 'Oval']
N_CLASSES    = len(CLASS_NAMES)
CLASS_COLORS = ['#3498DB', '#E74C3C', '#2ECC71', '#9B59B6', '#F39C12']

# ── Antenna experiment files ─────────────────────────────────
# Each file was generated by radar_shape_simple.m with a
# different N_ant value. One model is trained per file.
ANTENNA_EXPERIMENTS = [
    {'n_ant':  4, 'file': 'radar_shapes_N4.mat'},
    {'n_ant':  8, 'file': 'radar_shapes_N8.mat'},
    {'n_ant': 10, 'file': 'radar_shapes_N10.mat'},
    {'n_ant': 12, 'file': 'radar_shapes_N12.mat'},
    {'n_ant': 16, 'file': 'radar_shapes_N16.mat'},
    {'n_ant': 32, 'file': 'radar_shapes_N32.mat'},
]


# ============================================================
#  SECTION 1: LOAD DATASET
# ============================================================

def load_tensors(filepath):
    """
    Load one MATLAB dataset file once and return the raw tensors plus
    metadata. This is split from loader construction so that the same
    tensors can be reused across seeds without re-reading the .mat file.

    Args:
        filepath : path to .mat file

    Returns:
        tensors : dict with keys 'X_tr','Y_tr','X_vl','Y_vl','X_te','Y_te'
        meta    : dict with n_ant, filepath, and set sizes
    """
    if not os.path.exists(filepath):
        raise FileNotFoundError(
            f"\nDataset not found: {filepath}\n"
            f"Run radar_shape_simple.m in MATLAB first.\n"
            f"Make sure the antenna loop generates all four files."
        )

    print(f"\nLoading: {filepath}")

    # Try scipy first (works for MAT files up to v7.2).
    # Fall back to h5py for v7.3 (HDF5) files.
    try:
        data = scipy.io.loadmat(filepath)
        def prep(X, Y):
            X = np.expand_dims(X.astype(np.float32), axis=1)
            Y = Y.flatten().astype(np.int64) - 1
            return torch.tensor(X), torch.tensor(Y)
        X_tr, Y_tr = prep(data['X_train'], data['Y_train'])
        X_vl, Y_vl = prep(data['X_val'],   data['Y_val'])
        X_te, Y_te = prep(data['X_test'],  data['Y_test'])
        _n_ant_raw = data.get('N_ant', None)
        n_ant_from_file = int(np.array(_n_ant_raw).flatten()[0]) if _n_ant_raw is not None else None
    except NotImplementedError:
        # v7.3 HDF5 format — arrays are stored transposed relative to scipy
        with h5py.File(filepath, 'r') as f:
            def prep_h5(key_X, key_Y):
                X = np.array(f[key_X], dtype=np.float32)
                Y = np.array(f[key_Y], dtype=np.int64)
                # h5py transposes MATLAB arrays: shape is (cols, rows, ...)
                # For 2-D data stored as (range, angle, N) -> transpose to (N, range, angle)
                if X.ndim == 3:
                    X = X.transpose(2, 0, 1)   # (range, angle, N) -> (N, range, angle)
                elif X.ndim == 2:
                    X = X.T                     # (features, N) -> (N, features)
                X = np.expand_dims(X, axis=1)   # add channel dim
                Y = Y.flatten() - 1             # 1-indexed -> 0-indexed
                return torch.tensor(X), torch.tensor(Y)
            X_tr, Y_tr = prep_h5('X_train', 'Y_train')
            X_vl, Y_vl = prep_h5('X_val',   'Y_val')
            X_te, Y_te = prep_h5('X_test',  'Y_test')
            n_ant_from_file = int(np.array(f['N_ant']).flatten()[0]) if 'N_ant' in f else None

    # Read N_ant from file if saved, otherwise parse from filename
    if n_ant_from_file is not None:
        n_ant = n_ant_from_file
    else:
        basename = os.path.basename(filepath)
        try:
            n_ant = int(''.join(
                filter(str.isdigit,
                       basename.split('N')[-1].split('.')[0])
            ))
        except Exception:
            n_ant = -1

    print(f"  N_ant  : {n_ant}")
    print(f"  Train  : {X_tr.shape}")
    print(f"  Val    : {X_vl.shape}")
    print(f"  Test   : {X_te.shape}")
    print(f"\n  Class distribution (train):")
    for i, name in enumerate(CLASS_NAMES):
        n = (Y_tr == i).sum().item()
        bar = 'x' * (n // 10)
        print(f"    {i+1}. {name:12s}: {n:4d}  {bar}")

    tensors = {
        'X_tr': X_tr, 'Y_tr': Y_tr,
        'X_vl': X_vl, 'Y_vl': Y_vl,
        'X_te': X_te, 'Y_te': Y_te,
    }

    meta = {
        'n_ant'   : n_ant,
        'filepath': filepath,
        'n_train' : len(X_tr),
        'n_val'   : len(X_vl),
        'n_test'  : len(X_te),
    }

    return tensors, meta


def make_loaders(tensors, batch_size=256, seed=0):
    """
    Build DataLoaders from pre-loaded tensors. The train loader's
    shuffle is seeded via a torch.Generator so each seed sees a
    different batch order while the underlying data is shared.
    """
    gen = torch.Generator()
    gen.manual_seed(int(seed))

    train_dl = DataLoader(
        TensorDataset(tensors['X_tr'], tensors['Y_tr']),
        batch_size=batch_size,
        shuffle=True, drop_last=True,
        generator=gen,
    )
    val_dl = DataLoader(
        TensorDataset(tensors['X_vl'], tensors['Y_vl']),
        batch_size=512, shuffle=False,
    )
    test_dl = DataLoader(
        TensorDataset(tensors['X_te'], tensors['Y_te']),
        batch_size=512, shuffle=False,
    )
    return train_dl, val_dl, test_dl


def load_dataset(filepath, batch_size=256, seed=0):
    """
    Backwards-compatible helper: load + build loaders in one call.
    New code should prefer load_tensors + make_loaders so that the
    .mat file is read once per N_ant instead of once per seed.
    """
    tensors, meta = load_tensors(filepath)
    train_dl, val_dl, test_dl = make_loaders(tensors, batch_size=batch_size, seed=seed)
    return train_dl, val_dl, test_dl, meta


# ============================================================
#  SECTION 2: CNN ARCHITECTURE
#
#  Input:  [B x 1 x 512 x 256]
#  Output: [B x 5]
#
#  4 conv blocks -> Global Average Pooling -> 2 FC layers.
#  Same architecture used for ALL antenna experiments so
#  that accuracy differences reflect the data, not the model.
# ============================================================

class ShapeCNN(nn.Module):
    """
    2D CNN for radar shape classification.
    Architecture is fixed across all antenna experiments.
    Only the training data changes between experiments.
    """

    def __init__(self, n_classes=5):
        super().__init__()

        self.features = nn.Sequential(

            # Block 1: 7x7 kernel - detect broad shape structure
            nn.Conv2d(1, 16, kernel_size=7, padding=3),
            nn.BatchNorm2d(16),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2, 2),         # 512x256 -> 256x128

            # Block 2: 5x5 kernel - mid-level features
            nn.Conv2d(16, 32, kernel_size=5, padding=2),
            nn.BatchNorm2d(32),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2, 2),         # 256x128 -> 128x64

            # Block 3: 3x3 kernel - fine structure
            nn.Conv2d(32, 64, kernel_size=3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2, 2),         # 128x64 -> 64x32

            # Block 4: 3x3 kernel - high-level combinations
            nn.Conv2d(64, 128, kernel_size=3, padding=1),
            nn.BatchNorm2d(128),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2, 2),         # 64x32 -> 32x16
        )

        # Global Average Pooling: [B x 128 x 32 x 16] -> [B x 128 x 1 x 1]
        self.gap = nn.AdaptiveAvgPool2d(1)

        self.classifier = nn.Sequential(
            nn.Flatten(),               # [B x 128 x 1 x 1] -> [B x 128]
            nn.Linear(128, 64),
            nn.ReLU(inplace=True),
            nn.Dropout(0.4),
            nn.Linear(64, n_classes),   # [B x 64] -> [B x 5]
        )

    def forward(self, x):
        x = self.features(x)
        x = self.gap(x)
        x = self.classifier(x)
        return x


# ============================================================
#  SECTION 3: TRAINING
# ============================================================

def train_model(model, train_dl, val_dl, n_ant,
                n_epochs=40, lr=1e-3, patience=20, warmup_epochs=3):
    """
    Train one model on one dataset.

    Args:
        model         : ShapeCNN instance (freshly initialised)
        train_dl      : training DataLoader
        val_dl        : validation DataLoader
        n_ant         : antenna count (used for print labels only)
        n_epochs      : max training epochs
        lr            : target learning rate (after warmup)
        patience      : early stopping patience in epochs
        warmup_epochs : linear warmup length (0.1*lr -> lr)

    Returns:
        model   : best weights restored
        history : loss and accuracy per epoch

    Notes:
        Patience is set high (20) because the EMA val loss in this
        setup transiently spikes 2-3x mid-training before recovering,
        especially at high N_ant. A 3-epoch linear warmup suppresses
        the worst of those spikes by letting BatchNorm statistics
        settle before the LR hits its target.
    """
    model     = model.to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(),
                           lr=lr, weight_decay=1e-4)
    # LR schedule: linear warmup for `warmup_epochs`, then cosine
    # annealing from lr down to 1e-6 over the remaining epochs.
    # Warmup reduces the early-epoch val-loss spikes caused by
    # BatchNorm running-stat instability, which had been triggering
    # premature early-stopping at N_ant >= 10.
    warmup = optim.lr_scheduler.LinearLR(
        optimizer, start_factor=0.1, end_factor=1.0,
        total_iters=max(warmup_epochs, 1),
    )
    cosine = optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=max(n_epochs - warmup_epochs, 1),
        eta_min=1e-6,
    )
    scheduler = optim.lr_scheduler.SequentialLR(
        optimizer,
        schedulers=[warmup, cosine],
        milestones=[warmup_epochs],
    )

    history = {
        'train_loss'  : [], 'val_loss'    : [],
        'train_acc'   : [], 'val_acc'     : [],
        'val_loss_ema': [], 'val_acc_ema' : [],
    }
    ema_val_loss = None
    ema_val_acc  = None
    EMA_ALPHA    = 0.3          # 0 = fully smoothed, 1 = no smoothing

    best_val   = float('inf')
    best_wts   = None
    no_improve = 0

    print(f"\n{'='*62}")
    print(f"  Training | N_ant={n_ant} | {n_epochs} epochs | lr={lr}")
    print(f"{'='*62}")
    print(f"{'Ep':>4} | {'TrLoss':>8} | {'VaLoss':>8} | "
          f"{'TrAcc':>7} | {'VaAcc':>7} | {'LR':>9}")
    print(f"{'-'*62}")

    for ep in range(1, n_epochs + 1):
        t0 = time.time()

        # -- Train phase --
        model.train()
        tr_loss = tr_corr = tr_n = 0

        for Xb, Yb in train_dl:
            Xb, Yb = Xb.to(device), Yb.to(device)
            # Random horizontal flip with 50% probability per sample
            flip_mask = torch.rand(Xb.size(0)) > 0.5
            Xb[flip_mask] = torch.flip(Xb[flip_mask], dims=[-1])
            optimizer.zero_grad()
            out  = model(Xb)
            loss = criterion(out, Yb)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()

            tr_loss += loss.item() * Xb.size(0)
            tr_corr += (out.argmax(1) == Yb).sum().item()
            tr_n    += Xb.size(0)

        tr_loss /= tr_n
        tr_acc   = tr_corr / tr_n

        # -- Validation phase --
        model.eval()
        va_loss = va_corr = va_n = 0

        with torch.no_grad():
            for Xb, Yb in val_dl:
                Xb, Yb = Xb.to(device), Yb.to(device)
                out      = model(Xb)
                loss     = criterion(out, Yb)
                va_loss += loss.item() * Xb.size(0)
                va_corr += (out.argmax(1) == Yb).sum().item()
                va_n    += Xb.size(0)

        va_loss /= va_n
        va_acc   = va_corr / va_n

        # -- EMA smoothing of val metrics --
        # Damps per-epoch noise so training curves and early stopping
        # react to trends, not to single-batch spikes.
        if ema_val_loss is None:
            ema_val_loss = va_loss
            ema_val_acc  = va_acc
        else:
            ema_val_loss = EMA_ALPHA * va_loss + (1 - EMA_ALPHA) * ema_val_loss
            ema_val_acc  = EMA_ALPHA * va_acc  + (1 - EMA_ALPHA) * ema_val_acc

        scheduler.step()
        cur_lr = optimizer.param_groups[0]['lr']

        history['train_loss'].append(tr_loss)
        history['val_loss'].append(va_loss)
        history['train_acc'].append(tr_acc)
        history['val_acc'].append(va_acc)
        history['val_loss_ema'].append(ema_val_loss)
        history['val_acc_ema'].append(ema_val_acc)

        print(f"{ep:>4} | {tr_loss:>8.4f} | {va_loss:>8.4f} | "
              f"{tr_acc*100:>6.1f}% | {va_acc*100:>6.1f}% | "
              f"{cur_lr:>9.6f}  ({time.time()-t0:.1f}s)  "
              f"EMA_VaLoss={ema_val_loss:.4f}")

        # -- Early stopping (on smoothed val loss, not raw) --
        if ema_val_loss < best_val:
            best_val   = ema_val_loss
            best_wts   = {k: v.clone()
                          for k, v in model.state_dict().items()}
            no_improve = 0
        else:
            no_improve += 1
            if no_improve >= patience:
                print(f"\n  Early stopping at epoch {ep}.")
                break

    model.load_state_dict(best_wts)
    print(f"\n  Best val loss: {best_val:.4f}")
    return model, history


# ============================================================
#  SECTION 4: EVALUATION
# ============================================================

def evaluate_model(model, test_dl, n_ant):
    """Evaluate on test set and plot confusion matrix."""

    model.eval()
    all_preds  = []
    all_labels = []

    with torch.no_grad():
        for Xb, Yb in test_dl:
            out = model(Xb.to(device))
            all_preds.extend(out.argmax(1).cpu().numpy())
            all_labels.extend(Yb.numpy())

    preds  = np.array(all_preds)
    labels = np.array(all_labels)
    acc    = float(np.mean(preds == labels))

    print(f"\n  Test Accuracy (N_ant={n_ant}): {acc*100:.2f}%\n")
    print(classification_report(labels, preds,
                                 target_names=CLASS_NAMES,
                                 digits=3))

    # Confusion matrix plots
    cm      = confusion_matrix(labels, preds)
    cm_norm = cm.astype(float) / cm.sum(axis=1, keepdims=True)

    fig, axes = plt.subplots(1, 2, figsize=(13, 5))
    fig.suptitle(
        f'Confusion Matrix  |  N_ant={n_ant}  |  '
        f'Accuracy={acc*100:.1f}%',
        fontsize=13, fontweight='bold'
    )

    for ax, data, fmt, title in zip(
        axes,
        [cm, cm_norm],
        ['d', '.1%'],
        ['Counts', 'Normalised']
    ):
        sns.heatmap(data, annot=True, fmt=fmt, cmap='Blues',
                    xticklabels=CLASS_NAMES,
                    yticklabels=CLASS_NAMES,
                    ax=ax, linewidths=0.5, square=True)
        ax.set_xlabel('Predicted', fontsize=11)
        ax.set_ylabel('True',      fontsize=11)
        ax.set_title(title,        fontsize=11)

    plt.tight_layout()
    fname = f'confusion_N{n_ant}.png'
    plt.savefig(fname, dpi=150, bbox_inches='tight')
    plt.show()
    print(f"  Saved: {fname}")

    return acc, preds, labels


# ============================================================
#  SECTION 5: TRAINING HISTORY PLOT
# ============================================================

def plot_history(history, n_ant):
    """Plot loss and accuracy curves for one experiment."""

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))
    fig.suptitle(f'Training History  |  N_ant={n_ant}',
                 fontsize=13, fontweight='bold')

    eps = range(1, len(history['train_loss']) + 1)

    # Raw val curves in faded background; EMA curves in foreground.
    # Fall back to raw if EMA keys aren't in the history dict
    # (e.g. when loading legacy runs saved before EMA was added).
    has_ema = 'val_loss_ema' in history and len(history['val_loss_ema']) > 0

    ax1.plot(eps, history['train_loss'], 'b-o', ms=3, label='Train', alpha=0.85)
    if has_ema:
        ax1.plot(eps, history['val_loss'],     'r-',  lw=1, alpha=0.3,
                 label='Val (raw)')
        ax1.plot(eps, history['val_loss_ema'], 'r-o', ms=3,
                 label='Val (EMA)')
    else:
        ax1.plot(eps, history['val_loss'], 'r-o', ms=3, label='Val')
    ax1.set_xlabel('Epoch')
    ax1.set_ylabel('Loss')
    ax1.set_title('Loss')
    ax1.legend()
    ax1.grid(True, alpha=0.3)

    ax2.plot(eps, [a*100 for a in history['train_acc']],
             'b-o', ms=3, label='Train', alpha=0.85)
    if has_ema:
        ax2.plot(eps, [a*100 for a in history['val_acc']],
                 'r-', lw=1, alpha=0.3, label='Val (raw)')
        ax2.plot(eps, [a*100 for a in history['val_acc_ema']],
                 'r-o', ms=3, label='Val (EMA)')
    else:
        ax2.plot(eps, [a*100 for a in history['val_acc']],
                 'r-o', ms=3, label='Val')
    ax2.set_xlabel('Epoch')
    ax2.set_ylabel('Accuracy (%)')
    ax2.set_title('Accuracy')
    ax2.legend()
    ax2.grid(True, alpha=0.3)
    ax2.set_ylim([0, 105])

    plt.tight_layout()
    fname = f'history_N{n_ant}.png'
    plt.savefig(fname, dpi=150, bbox_inches='tight')
    plt.show()
    print(f"  Saved: {fname}")


# ============================================================
#  SECTION 6: ACCURACY vs ANTENNA COUNT COMPARISON PLOT
#
#  This is the key research result figure.
#  Shows how classification accuracy improves with more
#  antennas — directly answers the question:
#  "How many antennas do you need for reliable classification?"
# ============================================================

def plot_antenna_comparison(results):
    """
    Plot accuracy vs antenna count with per-seed scatter and
    mean ± std error bars.

    Args:
        results : list of dicts from run_antenna_experiments.
                  Each dict carries 'mean_acc', 'std_acc',
                  'accuracies' (per seed), 'per_class_mean',
                  'per_class_std', and 'seeds'.
    """
    n_ants     = [r['n_ant']    for r in results]
    means      = [r['mean_acc'] for r in results]
    stds       = [r['std_acc']  for r in results]

    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    fig.suptitle(
        'Shape Classification: Impact of Antenna Count',
        fontsize=14, fontweight='bold'
    )

    # -- Left: overall accuracy vs antenna count --
    ax = axes[0]

    # Faded scatter of each seed's test accuracy
    for r in results:
        ax.scatter(
            [r['n_ant']] * len(r['accuracies']),
            [a*100 for a in r['accuracies']],
            color='#3498DB', alpha=0.35, s=30, zorder=2
        )

    # Mean with ±1 std error bars
    ax.errorbar(
        n_ants, [m*100 for m in means], yerr=[s*100 for s in stds],
        fmt='o-', linewidth=2.5, markersize=10,
        markerfacecolor='white', markeredgewidth=2.5,
        color='#2C3E50', ecolor='#2C3E50', capsize=5, zorder=3,
        label='Mean ± 1 std'
    )

    for n, m, s in zip(n_ants, means, stds):
        ax.annotate(
            f'{m*100:.1f}±{s*100:.1f}%',
            xy=(n, m*100),
            xytext=(0, 14),
            textcoords='offset points',
            ha='center', fontsize=10,
            fontweight='bold', color='#2C3E50'
        )

    n_seeds_label = len(results[0]['seeds']) if results else 0
    ax.set_xlabel('Number of RX Antennas', fontsize=12)
    ax.set_ylabel('Test Accuracy (%)',      fontsize=12)
    ax.set_title(f'Overall Accuracy vs Antenna Count '
                 f'({n_seeds_label} seeds)',
                 fontsize=12, fontweight='bold')
    ax.set_xticks(n_ants)
    ax.set_ylim([40, 108])
    ax.grid(True, alpha=0.3)
    ax.axhline(100 / N_CLASSES, color='red',
               linestyle='--', alpha=0.5, linewidth=1.5,
               label=f'Chance ({100/N_CLASSES:.0f}%)')
    ax.legend(fontsize=10, loc='lower right')

    # Secondary x-axis showing angular resolution
    ax_top = ax.twiny()
    ax_top.set_xlim(ax.get_xlim())
    ax_top.set_xticks(n_ants)
    ax_top.set_xticklabels(
        [f'{114.6/n:.1f} deg' for n in n_ants],
        fontsize=9, color='gray'
    )
    ax_top.set_xlabel('Angular Resolution',
                       fontsize=10, color='gray')

    # -- Right: per-class accuracy grouped bar chart with error bars --
    ax     = axes[1]
    x      = np.arange(N_CLASSES)
    w      = 0.8 / max(len(results), 1)
    n_exp  = len(results)
    offsets = np.linspace(-(n_exp-1)*w/2, (n_exp-1)*w/2, n_exp)
    bar_colors = ['#3498DB', '#2ECC71', '#E74C3C', '#9B59B6',
                  '#F39C12', '#1ABC9C', '#8E44AD']

    for idx, (res, offset) in enumerate(zip(results, offsets)):
        pc_mean = res['per_class_mean']
        pc_std  = res['per_class_std']
        ax.bar(
            x + offset,
            [pc_mean.get(name, 0)*100 for name in CLASS_NAMES],
            yerr=[pc_std.get(name, 0)*100 for name in CLASS_NAMES],
            width=w,
            color=bar_colors[idx % len(bar_colors)],
            alpha=0.85,
            label=f"N={res['n_ant']}",
            ecolor='black', capsize=3, error_kw={'lw': 1.0}
        )

    ax.set_xlabel('Shape Class', fontsize=12)
    ax.set_ylabel('Accuracy (%)', fontsize=12)
    ax.set_title('Per-Class Accuracy by Antenna Count',
                 fontsize=12, fontweight='bold')
    ax.set_xticks(x)
    ax.set_xticklabels(CLASS_NAMES, fontsize=10)
    ax.set_ylim([0, 115])
    ax.legend(fontsize=9, loc='lower right', ncol=2)
    ax.grid(axis='y', alpha=0.3)
    ax.axhline(100, color='gray', linestyle='--',
               alpha=0.4, linewidth=1)

    plt.tight_layout()
    plt.savefig('accuracy_vs_antennas.png', dpi=150,
                bbox_inches='tight')
    plt.show()
    print("Saved: accuracy_vs_antennas.png")

    # Summary table
    print(f"\n{'='*70}")
    print(f"  ANTENNA EXPERIMENT SUMMARY (mean ± std across seeds)")
    print(f"{'='*70}")
    print(f"  {'N_ant':>6} | {'Resolution':>12} | {'Mean Acc':>10} | "
          f"{'Std':>6} | {'Best':>7}")
    print(f"  {'-'*62}")
    for r in results:
        res_deg = 114.6 / r['n_ant']
        print(f"  {r['n_ant']:>6} | {res_deg:>9.1f} deg | "
              f"{r['mean_acc']*100:>9.2f}% | "
              f"{r['std_acc']*100:>5.2f}% | "
              f"{r['best_accuracy']*100:>6.2f}%")
    print(f"{'='*70}\n")


# ============================================================
#  SECTION 7: SINGLE SAMPLE INFERENCE
# ============================================================

def predict_shape(heatmap, model, true_label=None):
    """
    Predict the shape of one radar heatmap.

    Args:
        heatmap   : numpy array [range_bins x angle_bins]
        model     : trained ShapeCNN
        true_label: int 0-4 if known (for display only)

    Returns:
        pred_name  : predicted shape name
        confidence : float 0-1
        all_probs  : dict of class name -> probability
    """
    model.eval()

    hm = heatmap.astype(np.float32)
    if hm.max() > 0:
        hm = hm / hm.max()

    # Resize to training dimensions if needed
    if hm.shape != (512, 256):
        from scipy.ndimage import zoom
        hm = zoom(hm, (512/hm.shape[0], 256/hm.shape[1]), order=1)
        hm = hm / (hm.max() + 1e-9)

    tensor = torch.tensor(hm).unsqueeze(0).unsqueeze(0).to(device)

    with torch.no_grad():
        logits = model(tensor)
        probs  = torch.softmax(logits, dim=1).cpu().numpy()[0]

    pred_idx   = int(np.argmax(probs))
    pred_name  = CLASS_NAMES[pred_idx]
    confidence = float(probs[pred_idx])
    all_probs  = {CLASS_NAMES[i]: float(probs[i])
                  for i in range(N_CLASSES)}

    # Console output
    print(f"\n{'='*45}")
    print(f"  RADAR SHAPE PREDICTION")
    print(f"{'='*45}")
    if true_label is not None:
        correct = 'CORRECT' if pred_idx == true_label else 'WRONG'
        print(f"  True shape  : {CLASS_NAMES[true_label]}")
        print(f"  Prediction  : {pred_name}  [{correct}]")
    else:
        print(f"  Prediction  : {pred_name}")
    print(f"  Confidence  : {confidence*100:.1f}%")
    print(f"\n  All probabilities:")
    for name, prob in sorted(all_probs.items(),
                              key=lambda x: -x[1]):
        bar = 'X' * int(prob * 30)
        print(f"    {name:12s}: {prob*100:5.1f}%  {bar}")
    print(f"{'='*45}\n")

    # Visualisation
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(11, 4))

    title_str = f"Prediction: {pred_name} ({confidence*100:.1f}%)"
    if true_label is not None:
        correct = pred_idx == true_label
        tag     = 'CORRECT' if correct else 'WRONG'
        title_str += f"  --  {tag}"
    fig.suptitle(title_str, fontsize=13, fontweight='bold')

    im = ax1.imshow(20*np.log10(hm + 1e-6),
                    cmap='jet', aspect='auto',
                    vmin=-40, vmax=0)
    plt.colorbar(im, ax=ax1, label='dB')
    ax1.set_xlabel('Angle bins')
    ax1.set_ylabel('Range bins')
    ax1.set_title('Input Heatmap')

    names      = list(all_probs.keys())
    probs_list = list(all_probs.values())
    colors     = [CLASS_COLORS[CLASS_NAMES.index(n)] for n in names]
    bars       = ax2.barh(names,
                          [p*100 for p in probs_list],
                          color=colors,
                          edgecolor='white',
                          height=0.6)
    bars[pred_idx].set_edgecolor('black')
    bars[pred_idx].set_linewidth(2.5)
    ax2.set_xlabel('Confidence (%)')
    ax2.set_xlim([0, 115])
    ax2.set_title('Class Probabilities')
    ax2.grid(axis='x', alpha=0.3)
    ax2.axvline(50, color='gray', linestyle='--', alpha=0.4)
    for b, p in zip(bars, probs_list):
        ax2.text(b.get_width()+1,
                 b.get_y() + b.get_height()/2,
                 f'{p*100:.1f}%', va='center', fontsize=9)

    plt.tight_layout()
    plt.savefig('shape_prediction.png', dpi=150,
                bbox_inches='tight')
    plt.show()

    return pred_name, confidence, all_probs


# ============================================================
#  SECTION 8: SAVE AND LOAD MODEL
# ============================================================

def save_model(model, n_ant, acc):
    """Save model weights and metadata to disk."""
    filepath = f'radar_shape_model_N{n_ant}.pt'
    torch.save({
        'model_state_dict': model.state_dict(),
        'class_names'     : CLASS_NAMES,
        'n_classes'       : N_CLASSES,
        'n_ant'           : n_ant,
        'test_accuracy'   : acc,
    }, filepath)
    print(f"  Model saved: {filepath}")
    return filepath


def load_model(filepath):
    """Load a saved model for inference."""
    if not os.path.exists(filepath):
        raise FileNotFoundError(f"Model not found: {filepath}")

    ckpt  = torch.load(filepath, map_location=device)
    model = ShapeCNN(n_classes=ckpt['n_classes'])
    model.load_state_dict(ckpt['model_state_dict'])
    model = model.to(device)
    model.eval()

    print(f"Loaded : {filepath}")
    print(f"  N_ant    : {ckpt.get('n_ant', 'unknown')}")
    print(f"  Accuracy : {ckpt.get('test_accuracy', 0)*100:.1f}%")

    return model, ckpt


# ============================================================
#  SECTION 9: PER-CLASS ACCURACY HELPER
# ============================================================

def per_class_accuracy(preds, labels):
    """Return accuracy dict keyed by class name."""
    acc_dict = {}
    for i, name in enumerate(CLASS_NAMES):
        mask = labels == i
        if mask.sum() > 0:
            acc_dict[name] = float(
                np.mean(preds[mask] == labels[mask])
            )
        else:
            acc_dict[name] = 0.0
    return acc_dict


# ============================================================
#  SECTION 10: RUN ALL ANTENNA EXPERIMENTS
# ============================================================

def run_antenna_experiments(experiments, seeds=None):
    """
    Train and evaluate one model per antenna dataset, repeated
    once per seed.

    For each (experiment, seed):
      1. Load dataset from .mat file (re-loaded each seed so the
         DataLoader shuffle also varies)
      2. Set global RNG seed
      3. Initialise a fresh ShapeCNN (new weights each seed)
      4. Train with early stopping
      5. Evaluate on test set
      6. Keep the best model of the N_ant (used for inference demo)

    After all seeds finish for a given N_ant:
      * Save the best model as radar_shape_model_N{N}.pt
      * Plot training curves overlaid across seeds
      * Plot confusion matrix from the best seed
      * Aggregate per-seed accuracies into mean ± std

    Args:
        experiments : list of dicts with 'n_ant' and 'file' keys
        seeds       : list of int seeds; defaults to module-level SEEDS

    Returns:
        results : list of result dicts (one per N_ant)
    """
    if seeds is None:
        seeds = SEEDS

    results = []

    for exp in experiments:
        n_ant    = exp['n_ant']
        filepath = exp['file']

        print(f"\n{'#'*62}")
        print(f"#  EXPERIMENT: N_ant = {n_ant}  |  seeds = {seeds}")
        print(f"#  File      : {filepath}")
        print(f"{'#'*62}")

        if not os.path.exists(filepath):
            print(f"  SKIPPED: {filepath} not found.")
            print(f"  Run the MATLAB data generator with N_ant={n_ant} first.")
            continue

        # Per-seed accumulators for this N_ant
        seed_accs       = []
        seed_histories  = []
        seed_per_class  = {name: [] for name in CLASS_NAMES}
        best_acc        = -1.0
        best_seed       = None
        best_model      = None
        best_preds      = None
        best_labels     = None

        # Load the .mat file ONCE for this N_ant; reuse across seeds.
        # Only the batch-shuffle RNG and the model init vary per seed.
        tensors, meta = load_tensors(filepath)

        for seed in seeds:
            print(f"\n  ---- seed {seed} ----")
            set_seed(seed)

            # Rebuild loaders per seed so the train shuffle order
            # varies; underlying tensors are shared (no disk I/O).
            train_dl, val_dl, test_dl = make_loaders(tensors, seed=seed)

            model  = ShapeCNN(n_classes=N_CLASSES)
            params = sum(p.numel() for p in model.parameters())
            if seed == seeds[0]:
                print(f"  ShapeCNN — {params:,} parameters")

            model, history = train_model(
                model, train_dl, val_dl,
                n_ant         = n_ant,
                n_epochs      = 60,
                lr            = 3e-4,
                patience      = 20,
                warmup_epochs = 3,
            )

            acc, preds, labels = evaluate_model(model, test_dl, n_ant)
            pc = per_class_accuracy(preds, labels)

            seed_accs.append(acc)
            seed_histories.append(history)
            for name in CLASS_NAMES:
                seed_per_class[name].append(pc.get(name, 0.0))

            if acc > best_acc:
                best_acc    = acc
                best_seed   = seed
                best_model  = model
                best_preds  = preds
                best_labels = labels

            print(f"  seed={seed}  |  acc={acc*100:.2f}%")

        # Aggregate across seeds
        mean_acc = float(np.mean(seed_accs))
        std_acc  = float(np.std(seed_accs, ddof=1)) if len(seed_accs) > 1 else 0.0
        pc_mean  = {n: float(np.mean(v))          for n, v in seed_per_class.items()}
        pc_std   = {n: float(np.std(v, ddof=1))
                    if len(v) > 1 else 0.0
                    for n, v in seed_per_class.items()}

        # Save best model + best-seed confusion matrix + history overlay
        save_model(best_model, n_ant, best_acc)
        plot_history_multi(seed_histories, n_ant, seeds)
        plot_confusion_from_preds(best_preds, best_labels, n_ant,
                                   best_acc, best_seed)

        results.append({
            'n_ant'          : n_ant,
            'seeds'          : list(seeds),
            'accuracies'     : seed_accs,
            'mean_acc'       : mean_acc,
            'std_acc'        : std_acc,
            'per_class_accs' : seed_per_class,
            'per_class_mean' : pc_mean,
            'per_class_std'  : pc_std,
            'histories'      : seed_histories,
            'best_model'     : best_model,
            'best_seed'      : best_seed,
            'best_accuracy'  : best_acc,
            # Back-compat keys used elsewhere
            'accuracy'       : mean_acc,
            'per_class_acc'  : pc_mean,
            'meta'           : meta,
        })

        print(f"\n  N_ant={n_ant} done  |  "
              f"mean acc = {mean_acc*100:.2f}% ± {std_acc*100:.2f}%  "
              f"(best seed {best_seed}: {best_acc*100:.2f}%)")

    return results


# ============================================================
#  SECTION 10a: AGGREGATION HELPERS
# ============================================================

def plot_history_multi(histories, n_ant, seeds):
    """
    Overlay training curves from several seeds for one N_ant.
    Each seed is drawn faded; a mean curve is drawn solid on top.
    EMA val curves are used when available.
    """
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))
    fig.suptitle(f'Training History (seeds={seeds})  |  N_ant={n_ant}',
                 fontsize=13, fontweight='bold')

    # Align lengths because early stopping can cut runs short
    min_len = min(len(h['train_loss']) for h in histories)
    eps     = range(1, min_len + 1)

    def stack(key):
        return np.stack([np.array(h[key][:min_len]) for h in histories])

    has_ema = all('val_loss_ema' in h and len(h['val_loss_ema']) > 0
                  for h in histories)

    tr_loss = stack('train_loss')
    va_loss = stack('val_loss_ema' if has_ema else 'val_loss')
    tr_acc  = stack('train_acc')  * 100
    va_acc  = stack('val_acc_ema' if has_ema else 'val_acc') * 100

    for i, h in enumerate(histories):
        ax1.plot(eps, h['train_loss'][:min_len],       'b-', lw=1, alpha=0.25)
        ax1.plot(eps, (h.get('val_loss_ema') or h['val_loss'])[:min_len],
                                                       'r-', lw=1, alpha=0.25)
        ax2.plot(eps, [a*100 for a in h['train_acc'][:min_len]],
                                                       'b-', lw=1, alpha=0.25)
        ax2.plot(eps, [a*100 for a in (h.get('val_acc_ema') or h['val_acc'])[:min_len]],
                                                       'r-', lw=1, alpha=0.25)

    ax1.plot(eps, tr_loss.mean(0), 'b-', lw=2, label='Train (mean)')
    ax1.plot(eps, va_loss.mean(0), 'r-', lw=2,
             label='Val (EMA mean)' if has_ema else 'Val (mean)')
    ax1.set_xlabel('Epoch'); ax1.set_ylabel('Loss')
    ax1.set_title('Loss'); ax1.legend(); ax1.grid(True, alpha=0.3)

    ax2.plot(eps, tr_acc.mean(0), 'b-', lw=2, label='Train (mean)')
    ax2.plot(eps, va_acc.mean(0), 'r-', lw=2,
             label='Val (EMA mean)' if has_ema else 'Val (mean)')
    ax2.set_xlabel('Epoch'); ax2.set_ylabel('Accuracy (%)')
    ax2.set_title('Accuracy'); ax2.legend(); ax2.grid(True, alpha=0.3)
    ax2.set_ylim([0, 105])

    plt.tight_layout()
    fname = f'history_N{n_ant}.png'
    plt.savefig(fname, dpi=150, bbox_inches='tight')
    plt.show()
    print(f"  Saved: {fname}")


def plot_confusion_from_preds(preds, labels, n_ant, acc, seed):
    """Plot a confusion matrix given already-computed preds/labels."""
    cm      = confusion_matrix(labels, preds)
    cm_norm = cm.astype(float) / cm.sum(axis=1, keepdims=True)

    fig, axes = plt.subplots(1, 2, figsize=(13, 5))
    fig.suptitle(
        f'Confusion Matrix  |  N_ant={n_ant}  |  '
        f'seed={seed}  |  Accuracy={acc*100:.1f}%',
        fontsize=13, fontweight='bold'
    )

    for ax, data, fmt, title in zip(
        axes, [cm, cm_norm], ['d', '.1%'], ['Counts', 'Normalised']
    ):
        sns.heatmap(data, annot=True, fmt=fmt, cmap='Blues',
                    xticklabels=CLASS_NAMES, yticklabels=CLASS_NAMES,
                    ax=ax, linewidths=0.5, square=True)
        ax.set_xlabel('Predicted'); ax.set_ylabel('True')
        ax.set_title(title)

    plt.tight_layout()
    fname = f'confusion_N{n_ant}.png'
    plt.savefig(fname, dpi=150, bbox_inches='tight')
    plt.show()
    print(f"  Saved: {fname}")


def save_results_csv(results, filepath='results_per_seed.csv'):
    """Dump per-seed results to CSV for the writeup."""
    rows = []
    for r in results:
        for seed, acc in zip(r['seeds'], r['accuracies']):
            row = {'n_ant': r['n_ant'], 'seed': seed,
                   'test_accuracy': acc}
            for name in CLASS_NAMES:
                idx = r['seeds'].index(seed)
                row[f'acc_{name}'] = r['per_class_accs'][name][idx]
            rows.append(row)

    if not rows:
        return

    fieldnames = list(rows[0].keys())
    with open(filepath, 'w', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)
    print(f"Saved per-seed results: {filepath}")


# ============================================================
#  SECTION 11: SINGLE FILE MODE
# ============================================================

def run_single(filepath, seeds=None):
    """
    Train on one .mat file across several seeds.
    Reuses run_antenna_experiments so the seed loop, aggregation,
    CSV dump and history-overlay plot stay identical to the sweep mode.
    """
    if seeds is None:
        seeds = SEEDS

    print(f"\nSingle-file mode: {filepath}  |  seeds = {seeds}")

    # Peek once to recover N_ant for labelling
    _, _, _, meta = load_dataset(filepath)
    n_ant = meta['n_ant']

    results = run_antenna_experiments(
        [{'n_ant': n_ant, 'file': filepath}],
        seeds=seeds,
    )

    if not results:
        return None, 0.0

    save_results_csv(results,
                     filepath=f'results_per_seed_N{n_ant}.csv')

    res       = results[0]
    best_model = res['best_model']

    # Demo: one sample per class using tensors reloaded from the same file
    raw       = scipy.io.loadmat(filepath) \
        if filepath.endswith('.mat') and not _is_hdf5_mat(filepath) \
        else None

    if raw is not None:
        X_test_np = raw['X_test'].astype(np.float32)
        Y_test_np = raw['Y_test'].flatten().astype(int) - 1

        print("\nDemo inference — one sample per class:")
        for cls in range(N_CLASSES):
            idx = np.where(Y_test_np == cls)[0][0]
            predict_shape(X_test_np[idx], best_model, true_label=cls)

    return best_model, res['mean_acc']


def _is_hdf5_mat(filepath):
    """True if the .mat is MATLAB v7.3 (HDF5) — can't be read by scipy.io."""
    try:
        with open(filepath, 'rb') as f:
            return f.read(8).startswith(b'\x89HDF')
    except Exception:
        return False


# ============================================================
#  SECTION 12: ENTRY POINT
# ============================================================

if __name__ == '__main__':

    parser = argparse.ArgumentParser()
    parser.add_argument(
        '--single', type=str, default=None, metavar='FILE',
        help='Train on one .mat file instead of all experiments'
    )
    parser.add_argument(
        '--seeds', type=str, default=None, metavar='LIST',
        help='Comma-separated list of RNG seeds, e.g. "0,1,2". '
             'Defaults to the module-level SEEDS list.'
    )
    parser.add_argument(
        '--N_ant', type=str, default=None, metavar='LIST',
        help='Comma-separated list of antenna counts to run, e.g. '
             '"10,12,16,32". Defaults to every entry in '
             'ANTENNA_EXPERIMENTS. Use this to skip already-finished '
             'runs without editing the experiment table.'
    )
    args = parser.parse_args()

    # Parse --seeds override
    if args.seeds is not None:
        try:
            seeds_override = [int(s.strip()) for s in args.seeds.split(',') if s.strip()]
        except ValueError:
            raise SystemExit(f"Invalid --seeds value: {args.seeds!r}")
        if not seeds_override:
            raise SystemExit("--seeds must list at least one integer")
    else:
        seeds_override = SEEDS

    # Parse --N_ant filter
    if args.N_ant is not None:
        try:
            n_ant_filter = {int(s.strip()) for s in args.N_ant.split(',') if s.strip()}
        except ValueError:
            raise SystemExit(f"Invalid --N_ant value: {args.N_ant!r}")
        experiments = [e for e in ANTENNA_EXPERIMENTS if e['n_ant'] in n_ant_filter]
        missing = n_ant_filter - {e['n_ant'] for e in experiments}
        if missing:
            print(f"Warning: --N_ant values not in ANTENNA_EXPERIMENTS: "
                  f"{sorted(missing)}")
        if not experiments:
            raise SystemExit("--N_ant filtered out every experiment")
    else:
        experiments = ANTENNA_EXPERIMENTS

    if args.single:
        run_single(args.single, seeds=seeds_override)

    else:
        print("="*62)
        print("  RADAR SHAPE CLASSIFICATION — ANTENNA EXPERIMENTS")
        print("  One model trained per antenna count dataset")
        print("="*62)

        print("\nFiles expected:")
        for exp in experiments:
            status = 'found' if os.path.exists(exp['file']) else 'MISSING'
            print(f"  N={exp['n_ant']:2d}  {exp['file']}  [{status}]")

        results = run_antenna_experiments(experiments,
                                           seeds=seeds_override)

        if len(results) == 0:
            print("\nNo experiments completed.")
            print("Generate all four .mat files in MATLAB first.")

        elif len(results) == 1:
            print("\nOnly one experiment completed.")
            print("Add more antenna datasets for the comparison plot.")

        else:
            # Comparison plot across all completed experiments
            plot_antenna_comparison(results)

            # Dump per-seed results to CSV for the writeup
            save_results_csv(results)

            # Demo inference using the best model (best mean across seeds)
            best   = max(results, key=lambda r: r['mean_acc'])
            n_best = best['n_ant']
            print(f"\nBest: N_ant={n_best} "
                  f"({best['mean_acc']*100:.1f}% mean accuracy "
                  f"± {best['std_acc']*100:.1f}%, "
                  f"best seed = {best['best_seed']}: "
                  f"{best['best_accuracy']*100:.1f}%)")

            raw       = scipy.io.loadmat(f'radar_shapes_N{n_best}.mat')
            X_test_np = raw['X_test'].astype(np.float32)
            Y_test_np = raw['Y_test'].flatten().astype(int) - 1

            print(f"\nDemo inference on best model (N={n_best}):")
            for cls in range(N_CLASSES):
                idx = np.where(Y_test_np == cls)[0][0]
                predict_shape(X_test_np[idx],
                              best['best_model'],
                              true_label=cls)

        print("\n" + "="*55)
        print("  USING A SAVED MODEL ON NEW DATA")
        print("="*55)
        print("""
  from radar_shape_simple_cnn import load_model, predict_shape
  import scipy.io

  # Load the best model
  model, ckpt = load_model('radar_shape_model_N16.pt')

  # Load a new heatmap from MATLAB
  data    = scipy.io.loadmat('real_heatmap.mat')
  heatmap = data['RA_normalised']   # [512 x 256]

  # Predict
  shape, conf, probs = predict_shape(heatmap, model)
  print(f'Shape: {shape}  Confidence: {conf*100:.1f}%')
        """)
